### ISSUE TITLE
Pete + Chris Importer Discussion

### ISSUE THREAD

**Issue by ChrisArasin** [bluecadet/amon-carter-web#69]

**Comment by ChrisArasin** [comment]
@pingevt Let's try to chat early next week about:
1. balancing your extended Bucknell time with Amon Carter leadership
2. Along with this might be Dan's involvement as Betina and I are splitting some time onto HIA.
3. Do we want to use the importer

**Comment by pingevt** [comment]
@ChrisArasin Sounds good... I'd like to use this project to start standardizing field names, etc in drupal with the fractal components we have saucepot. So I think using the importer would be a good start for that.
